### ISSUE TITLE
Test openlight_gateway

### ISSUE THREAD

**Issue by remisarrailh** [usini/usini-sketchs#2]
Need to create settings for buttons
--> Disable
--> Buttons (no pullup)
--> Buttons input pullup

**Comment by maditnerd** [comment]
Need to create settings for buttons
--> Disable
--> Buttons (no pullup)
--> Buttons input pullup

**Comment by remisarrailh** [comment]
2d8c711cf7b15cec91178c2380ae8460c860d949
